'use client';

// Importation des modules
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { DOCS_LINK_PREFETCH } from '../../constants';
import './DocsSidebar.scss';

// =================================================================
// DOCS SIDEBAR — navigation dans les sections de la documentation
// =================================================================
// Composant client pour une seule raison : il doit connaître le chemin courant afin de
// marquer l'entrée active. Tout le reste est statique.
//
// L'arbre arrive en PROP et non par import : le layout le tient déjà, et cette sidebar
// est identique sur toutes les pages — un import ne ferait qu'ajouter un couplage sans
// rien économiser. Les trois autres composants du chrome, eux, dépendent du chemin et
// importent l'index directement (cf. DocsToc).

/**
 * Section navigation of the documentation site.
 *
 * @param {Object} props - Component props.
 * @param {Array<{title: string, path: string, description: string, items: Array<Object>}>} props.sections -
 *   Sections in display order, as generated by scripts/build-docs-index.js.
 * @returns {JSX.Element} The rendered sidebar.
 */
const DocsSidebar = ({ sections = [] }) => {
    const pathname = usePathname();

    /**
     * Tells whether a path is the one currently displayed.
     *
     * Comparaison stricte, et non « commence par » : une section et sa première page
     * seraient sinon actives en même temps.
     *
     * @param {string} path - Path of a navigation entry.
     * @returns {boolean} True when it is the current page.
     */
    const isCurrent = (path) => pathname === path;

    return (
        <nav className="docs-sidebar" aria-label="Sections de la documentation">
            {sections.map((section) => (
                <section key={section.path} className="docs-sidebar__section">
                    <Link
                        prefetch={DOCS_LINK_PREFETCH}
                        href={section.path}
                        className="docs-sidebar__section-title"
                        aria-current={isCurrent(section.path) ? 'page' : undefined}
                    >
                        {section.title}
                    </Link>

                    {section.items.length > 0 && (
                        <ul className="docs-sidebar__list">
                            {section.items.map((item) => (
                                <li key={item.path}>
                                    <Link
                                        prefetch={DOCS_LINK_PREFETCH}
                                        href={item.path}
                                        className="docs-sidebar__link"
                                        aria-current={isCurrent(item.path) ? 'page' : undefined}
                                    >
                                        {item.title}
                                    </Link>
                                </li>
                            ))}
                        </ul>
                    )}
                </section>
            ))}
        </nav>
    );
};

export default DocsSidebar;
