'use client';

import React from 'react';
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Header from '../features/header/components/Header/Header';
import ThemeProvider from '../features/theme/providers/ThemeProvider';
import navigationData from '../../config/navigation_new.json';
import Footer from '../features/footer/components/Footer/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  /**
   * Handle navigation item clicks.
   * 
   * @param {Object} item - The clicked navigation item
   */
  const handleNavigationClick = (item) => {
      console.log('Navigation item clicked:', item);
      // Ici vous pourriez ajouter de la logique personnalisée
      // comme des analytics, notifications, etc.
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {/* Header avec les données de navigation_new.json */}
          <Header 
              navigationData={navigationData.main_menu}
              onNavigationItemClick={handleNavigationClick}
          />
          {children}
          <Footer copyrightText="© 2024 Dashboard Template" />
        </ThemeProvider>
      </body>
    </html>
  );
}
